apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: li3d

resources:
  - namespace.yaml
  - server-pvc.yaml
  - server-deployment.yaml
  - server-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

configMapGenerator:
  - name: li3d-server-config
    envs:
      - server-config.env

secretGenerator:
  - name: li3d-server-secrets
    envs:
      - secrets/server.env

generatorOptions:
  disableNameSuffixHash: false

images:
  - name: li3d-server
    newName: li3d-server
    newTag: latest
  - name: li3d-web
    newName: li3d-web
    newTag: latest
